// <auto-generated />
using System;
using Apartment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apartment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706022931_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Apartment.Models.Entities.Amenity", b =>
                {
                    b.Property<int>("AmenityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AmenityID");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            AmenityID = 1,
                            Name = "WiFi"
                        },
                        new
                        {
                            AmenityID = 2,
                            Name = "แอร์"
                        },
                        new
                        {
                            AmenityID = 3,
                            Name = "เครื่องซักผ้า"
                        },
                        new
                        {
                            AmenityID = 4,
                            Name = "ที่จอดรถ"
                        },
                        new
                        {
                            AmenityID = 5,
                            Name = "กล้องวงจรปิด"
                        },
                        new
                        {
                            AmenityID = 6,
                            Name = "ร้านสะดวกซื้อ"
                        },
                        new
                        {
                            AmenityID = 7,
                            Name = "ฟิตเนส"
                        });
                });

            modelBuilder.Entity("Apartment.Models.Entities.DormAmenity", b =>
                {
                    b.Property<int>("DormAmenityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DormAmenityID"));

                    b.Property<int>("AmenityID")
                        .HasColumnType("int");

                    b.Property<int>("DormID")
                        .HasColumnType("int");

                    b.HasKey("DormAmenityID");

                    b.HasIndex("AmenityID");

                    b.HasIndex("DormID");

                    b.ToTable("DormAmenities");
                });

            modelBuilder.Entity("Apartment.Models.Entities.DormHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DormID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HistoryID");

                    b.HasIndex("DormID");

                    b.ToTable("DormHistories");
                });

            modelBuilder.Entity("Apartment.Models.Entities.Dormitory", b =>
                {
                    b.Property<int>("DormID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DormID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DormName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerID")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DormID");

                    b.HasIndex("OwnerID");

                    b.HasIndex("RoomTypeID");

                    b.ToTable("Dormitories");
                });

            modelBuilder.Entity("Apartment.Models.Entities.RoomType", b =>
                {
                    b.Property<int>("RoomTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoomTypeID");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            RoomTypeID = 1,
                            Name = "ห้องเดี่ยว"
                        },
                        new
                        {
                            RoomTypeID = 2,
                            Name = "ห้องคู่"
                        });
                });

            modelBuilder.Entity("Apartment.Models.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "admin@npru.ac.th",
                            Name = "Admin",
                            PasswordHash = "$2a$11$4G1x5/N3B.WHHDrGG6a4vuiH.B7LixQYFppacceYsbso81qJIu8WG",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Apartment.Models.Entities.DormAmenity", b =>
                {
                    b.HasOne("Apartment.Models.Entities.Amenity", "Amenity")
                        .WithMany("DormAmenities")
                        .HasForeignKey("AmenityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apartment.Models.Entities.Dormitory", "Dormitory")
                        .WithMany("DormAmenities")
                        .HasForeignKey("DormID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Dormitory");
                });

            modelBuilder.Entity("Apartment.Models.Entities.DormHistory", b =>
                {
                    b.HasOne("Apartment.Models.Entities.Dormitory", "Dormitory")
                        .WithMany("Histories")
                        .HasForeignKey("DormID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dormitory");
                });

            modelBuilder.Entity("Apartment.Models.Entities.Dormitory", b =>
                {
                    b.HasOne("Apartment.Models.Entities.User", "Owner")
                        .WithMany("Dormitories")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apartment.Models.Entities.RoomType", "RoomType")
                        .WithMany("Dormitories")
                        .HasForeignKey("RoomTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("Apartment.Models.Entities.Amenity", b =>
                {
                    b.Navigation("DormAmenities");
                });

            modelBuilder.Entity("Apartment.Models.Entities.Dormitory", b =>
                {
                    b.Navigation("DormAmenities");

                    b.Navigation("Histories");
                });

            modelBuilder.Entity("Apartment.Models.Entities.RoomType", b =>
                {
                    b.Navigation("Dormitories");
                });

            modelBuilder.Entity("Apartment.Models.Entities.User", b =>
                {
                    b.Navigation("Dormitories");
                });
#pragma warning restore 612, 618
        }
    }
}
