// <auto-generated />
using System;
using Apartment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apartment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Apartment.Models.Entities.Amenity", b =>
                {
                    b.Property<int>("AmenityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AmenityID");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            AmenityID = 1,
                            Category = "ในห้อง",
                            Name = "แอร์"
                        },
                        new
                        {
                            AmenityID = 2,
                            Category = "ในห้อง",
                            Name = "ทีวี"
                        },
                        new
                        {
                            AmenityID = 3,
                            Category = "ในห้อง",
                            Name = "ตู้เย็น"
                        },
                        new
                        {
                            AmenityID = 4,
                            Category = "ในห้อง",
                            Name = "เฟอร์นิเจอร์พร้อมอยู่"
                        },
                        new
                        {
                            AmenityID = 5,
                            Category = "อินเตอร์เน็ต",
                            Name = "อินเตอร์เน็ตฟรี"
                        },
                        new
                        {
                            AmenityID = 6,
                            Category = "อินเตอร์เน็ต",
                            Name = "อินเตอร์เน็ตมีค่าบริการ"
                        },
                        new
                        {
                            AmenityID = 7,
                            Category = "ซักผ้า",
                            Name = "เครื่องซักผ้าภายในหอพัก"
                        },
                        new
                        {
                            AmenityID = 8,
                            Category = "ความปลอดภัย",
                            Name = "กล้องวงจรปิด"
                        },
                        new
                        {
                            AmenityID = 9,
                            Category = "ความปลอดภัย",
                            Name = "คีย์การ์ด / รหัสเข้าห้อง"
                        },
                        new
                        {
                            AmenityID = 10,
                            Category = "ส่วนกลาง",
                            Name = "ที่จอดรถ"
                        },
                        new
                        {
                            AmenityID = 11,
                            Category = "ส่วนกลาง",
                            Name = "ฟิตเนส"
                        },
                        new
                        {
                            AmenityID = 12,
                            Category = "ส่วนกลาง",
                            Name = "สระว่ายน้ำ"
                        });
                });

            modelBuilder.Entity("Apartment.Models.Entities.DormAmenity", b =>
                {
                    b.Property<int>("DormAmenityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DormAmenityID"));

                    b.Property<int>("AmenityID")
                        .HasColumnType("int");

                    b.Property<int>("DormID")
                        .HasColumnType("int");

                    b.HasKey("DormAmenityID");

                    b.HasIndex("AmenityID");

                    b.HasIndex("DormID");

                    b.ToTable("DormAmenities");
                });

            modelBuilder.Entity("Apartment.Models.Entities.DormHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DormID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HistoryID");

                    b.HasIndex("DormID");

                    b.ToTable("DormHistories");
                });

            modelBuilder.Entity("Apartment.Models.Entities.DormImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<int>("DormID")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ImageID");

                    b.HasIndex("DormID");

                    b.ToTable("DormImages");
                });

            modelBuilder.Entity("Apartment.Models.Entities.DormRoomType", b =>
                {
                    b.Property<int>("DormRoomTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DormRoomTypeID"));

                    b.Property<int>("DormID")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeID")
                        .HasColumnType("int");

                    b.HasKey("DormRoomTypeID");

                    b.HasIndex("DormID");

                    b.HasIndex("RoomTypeID");

                    b.ToTable("DormRoomTypes");
                });

            modelBuilder.Entity("Apartment.Models.Entities.Dormitory", b =>
                {
                    b.Property<int>("DormID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DormID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DormName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerID")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DormID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Dormitories");
                });

            modelBuilder.Entity("Apartment.Models.Entities.RoomType", b =>
                {
                    b.Property<int>("RoomTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoomTypeID");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            RoomTypeID = 1,
                            Category = "ประเภทเตียง",
                            Name = "เตียงเดี่ยว"
                        },
                        new
                        {
                            RoomTypeID = 2,
                            Category = "ประเภทเตียง",
                            Name = "เตียงคู่"
                        },
                        new
                        {
                            RoomTypeID = 3,
                            Category = "ประเภทสัญญา",
                            Name = "รายวัน"
                        },
                        new
                        {
                            RoomTypeID = 4,
                            Category = "ประเภทสัญญา",
                            Name = "รายเดือน"
                        });
                });

            modelBuilder.Entity("Apartment.Models.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "admin@npru.ac.th",
                            Name = "Admin",
                            PasswordHash = "$2a$11$4G1x5/N3B.WHHDrGG6a4vuiH.B7LixQYFppacceYsbso81qJIu8WG",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Apartment.Models.Entities.DormAmenity", b =>
                {
                    b.HasOne("Apartment.Models.Entities.Amenity", "Amenity")
                        .WithMany("DormAmenities")
                        .HasForeignKey("AmenityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apartment.Models.Entities.Dormitory", "Dormitory")
                        .WithMany("DormAmenities")
                        .HasForeignKey("DormID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Dormitory");
                });

            modelBuilder.Entity("Apartment.Models.Entities.DormHistory", b =>
                {
                    b.HasOne("Apartment.Models.Entities.Dormitory", "Dormitory")
                        .WithMany("Histories")
                        .HasForeignKey("DormID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dormitory");
                });

            modelBuilder.Entity("Apartment.Models.Entities.DormImage", b =>
                {
                    b.HasOne("Apartment.Models.Entities.Dormitory", "Dormitory")
                        .WithMany("Images")
                        .HasForeignKey("DormID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dormitory");
                });

            modelBuilder.Entity("Apartment.Models.Entities.DormRoomType", b =>
                {
                    b.HasOne("Apartment.Models.Entities.Dormitory", "Dormitory")
                        .WithMany("DormRoomTypes")
                        .HasForeignKey("DormID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apartment.Models.Entities.RoomType", "RoomType")
                        .WithMany("DormRoomTypes")
                        .HasForeignKey("RoomTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dormitory");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("Apartment.Models.Entities.Dormitory", b =>
                {
                    b.HasOne("Apartment.Models.Entities.User", "Owner")
                        .WithMany("Dormitories")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Apartment.Models.Entities.Amenity", b =>
                {
                    b.Navigation("DormAmenities");
                });

            modelBuilder.Entity("Apartment.Models.Entities.Dormitory", b =>
                {
                    b.Navigation("DormAmenities");

                    b.Navigation("DormRoomTypes");

                    b.Navigation("Histories");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Apartment.Models.Entities.RoomType", b =>
                {
                    b.Navigation("DormRoomTypes");
                });

            modelBuilder.Entity("Apartment.Models.Entities.User", b =>
                {
                    b.Navigation("Dormitories");
                });
#pragma warning restore 612, 618
        }
    }
}
